### ISSUE TITLE
Mesh-UI Configuration

### ISSUE THREAD

**Issue by philippguertler** [gentics/mesh-ui#119]
Currently there is no way to configure the new Mesh-UI. In the old version, the user could define some options in a `mesh-ui-config.js`.
Some options are not needed anymore (aloha editor config), while others are still relevant:
* Default language (could be replaced by a new endpoint in mesh which returns the configured default language)
* Custom micronode fields. See also #48 
* Node preview. See #57

**Comment by pschulzk** [comment]
Solved in version 0.10.6
