### ISSUE TITLE
Conflict resolution

### ISSUE THREAD

**Issue by philippguertler** [gentics/mesh-ui#122]
Some types of fields are not displayed correctly:
* Boolean lists: Shows true of false instead of checkboxes
* Micronodes: Shows [Object object]
* Fields are not ordered. However, this seems to be an issue with Mesh. The conflicts in the response are already not ordered. I expected it to be the same order as the fields are defined in the schema

**Comment by pschulzk** [comment]
In the latest UI version 0.10.6 this issues are fixed for content and schema editors.
However, the existing behavior of Mesh not saving fields array order persists: https://github.com/gentics/mesh/issues/721
