### ISSUE TITLE
Language of display fields in node browser

### ISSUE THREAD

**Issue by philippguertler** [gentics/mesh-ui#131]
# Description
When displaying nodes in the browser, the display name is used as the text for the node. However only the default language of the node is displayed. This could be unwanted.

# Possible solutions
* Keep it in default language
* Prefer the same language where the browser was opened
* Add a language switcher to the node browser (possibly confusing, since language does not matter in node references)

**Comment by pschulzk** [comment]
Solved in v0.10.6
