### ISSUE TITLE
Cannot create empty node

### ISSUE THREAD

**Issue by philippguertler** [gentics/mesh-ui#159]
Reproducer:
1. Create the following schema:
```
{
    "name": "StringFieldSchema",
    "fields": [
        {
            "name": "sfield",
            "required": false,
            "type": "string"
        }
    ]
}
```
2. Assign the schema to the project
3. Create a node of that schema
4. Try to press the save button. It will not work because it is grayed out.

**Comment by pschulzk** [comment]
Solved in v0.10.6 .
