### ISSUE TITLE
Editing user permissions loses state and is inconsistent

### ISSUE THREAD

**Issue by Skrylar** [gentics/mesh-ui#175]
## Gentics Mesh Version, operating system, or hardware.
- v0.27.1

## Operating System
- Linux

## JVM
- Open JDK 1.8.0_192

## Problem
Editing permissions for a role _appears_ to work, but navigating away from the page and back to it results in all of those fields showing blank checkboxes.

It is also possible for the test user to publish content he only has create permissions for, even though he doesn't have publish permissions for the project/container.

## Reproducer
Create a test user, a new group, a new role, assign test role to test group, and test user to new test group. Give create/update/read but not publish permissions. Also give read/create on a schema and read on folder schema. In a Firefox private window, log in as new user; he can create nodes of a schema without create/update permission to that schema (containers) and he can create and publish nodes from the schema he does have create to (even without publish permission.)

## Expected behaviour and actual behaviour
I would expect the user not to have, or for the publish button to be disabled. I would also expect the UI not to offer permission to create a node without create permission. I also expect that when re-entering the role GUI, that granted permissions have their tick boxes (which seem to reset to blanks even though the permissions are either active or not being enforced?)

**Comment by philippguertler** [comment]
We have released our new UI last week. The permissions are now loaded via GraphQL and also improvements have been made regarding caching in Mesh. This should now not be an issue anymore. If it still happens, please open another issue.
