### ISSUE TITLE
Selecting item in list resets current page to 1

### ISSUE THREAD

**Issue by pschulzk** [gentics/mesh-ui#194]
This issue addresses branch [develop](https://github.com/gentics/mesh-ui/tree/develop).

## Current behavior
In case of editor item list containing multiple pages, navigating to page n > 1 and selecting an item to open its details/editor view will result in flipping back to page 1.

## Expected behavior
Selecting an item to open its details/editor view won't affect item list pagination at all.

**Comment by philippguertler** [comment]
Fixed with https://github.com/gentics/mesh-ui/pull/259
