### ISSUE TITLE
Mesh UI Review

### ISSUE THREAD

**Issue by Jotschi** [gentics/mesh-ui#197]
Rev: fc32137996 (schema-builder)

* Project update dialog unclear. I initially did not get that the first field is editable/savable.
* Stat issue: Changing the project name and assigning a schema will not work. The state still references the old project name.
* Number fields are `0` when creating a new node.
* Opening the node reference field dialog and closing it again will result in a broken state. The node can't be saved.
* The Discard changes dialog lists `list changed` for vehicleImage. What does this mean? The node ref is not a  list but a single node reference.
* It is unclear how to select nodes in the node select dialog. The icon does not display a checkbox. Using a checkbox would be much clearer.
* UI Messages overlay with UI interaction elements. Thus preventing the usage of those elements as long as the messages are displayed.
* Errors due to upload conflicts are not clear.
* User creation dialog does not provide two password boxes to confirm the password
* User dialog does not show password boxes after creation. No way to change password.
* Assigning roles to groups does not provide UI feedback. The operation takes some time and later changes the state of the displayed table.

**Comment by pschulzk** [comment]
This issue collection will be closed in favor of issues dedicated to the mentioned problems still relevant in v.0.10.6:
#209 #43 #205
