### ISSUE TITLE
New UI Feedback

### ISSUE THREAD

**Issue by Jotschi** [gentics/mesh-ui#20]
* We currently have an issue that user inactivity causes the session to die and the ui can no longer be used. Usually occurs after 30min. We need to prevent this in the new ui.
* It is currently very cumbersome to create new fields in a document. You need to scroll down. Create the field and move it up to the place where you want it. It would be better to have an option to create a new field in between other fields.
* Image Upload may fail if the upload exceeds the limit. This error case must be handled and correctly shown in the UI.
* It is not clear that closing the current admin ui admin interface area returns you back to the nodes view
  I would expect that switching the admin ui lang would only affect the i18n keys of the interface and not the content. I would expect to see en, de... langs for each node in the nodes list.
* Fields for filesize are stored as a number of bytes which can be very long and therefore hard to read. (f.e. 300 GB is displayed as 3000000000)
* Schemas, Users, Groups, etc: There is no paging at the moment (only shows first 25, no way to go to second page)

**Comment by philippguertler** [comment]
When node is publish, all parent nodes must be published as well. Currently the error message is not very clear. It would also be nice to provide the option to publish all parent nodes in this case.

**Comment by bernhardriegler** [comment]
The schema "binary_content" is shipped with Mesh.
The segment field is set to the field "binary".
In order to use the webroot endpoint editors "need to know" the name of the binary file, as this will be used for the path. --> the name of the file in the binary field should be displayed (especially for images)

Displaying the webroot path for any node when the node is edited/viewed would also solve this requirement

**Comment by bernhardriegler** [comment]
Usermanagement: 
There should be a way to create an user account and make the user reset the password after the next login.
This could also be for users to retrieve a lost password.

**Comment by bernhardriegler** [comment]
Schema editor:
When adding a new field the cursor/focus should be set to the first input of the new field (i.e. name)

**Comment by Jotschi** [comment]
Relates to: https://github.com/gentics/mesh/issues/291

**Comment by bernhardriegler** [comment]
List of nodes in containers should be sorted alphabetically by the displayed value in the UI (displayname or uuid)

**Comment by Jotschi** [comment]
Sorting is not yet implemented in the mesh server.

**Comment by pschulzk** [comment]
This issue collection will be closed in favor of issues dedicated to the mentioned problems which are still relevant in v.0.10.6:
#43 #203 #205 #206 #207 #208
