### ISSUE TITLE
Display node webroot path

### ISSUE THREAD

**Issue by pschulzk** [gentics/mesh-ui#208]
The schema "binary_content" is shipped with Mesh.
The segment field is set to the field "binary".
In order to use the webroot endpoint editors "need to know" the name of the binary file, as this will be used for the path. --> the name of the file in the binary field should be displayed (especially for images)

Displaying the webroot path for any node when the node is edited/viewed would also solve this requirement

**Comment by philippguertler** [comment]
The name of the binary is already displayed.

![image](https://user-images.githubusercontent.com/13328856/61444118-1155fc80-a94b-11e9-9658-1c1ab6afe637.png)

I will look into displaying the whole path.
