### ISSUE TITLE
Production build: micronodes missing in editor

### ISSUE THREAD

**Issue by mephinet** [gentics/mesh-ui#233]
Using the new Mesh UI (develop branch, revision be9ba94f
) in development mode (e.g. with `yarn start` or `ng serve --proxy-config proxy.conf.json`) the node editor works fine for me. However, when switching to production mode (by adding `--prod`), the Mesh UI no longer displays microschemas when editing nodes.
No relevant errors in the console.
Firefox 67.0.4 (64-bit) on Arch Linux.

**Comment by philippguertler** [comment]
Was the field a list field? For me it seems that no list field is rendered at all in production mode.

**Comment by philippguertler** [comment]
It works with `ng serve` and `ng build --prod`. Only `ng serve --proxy-config proxy.conf.json --prod` refuses to show list fields.

**Comment by philippguertler** [comment]
I believe the circular dependency between `get-control-type.ts` and `list-field-component.ts` causes this issue.
