### ISSUE TITLE
No checkmarks shown in Schema to Project assignments

### ISSUE THREAD

**Issue by bebebee** [gentics/mesh-ui#274]
In: Admin UI -> Projects -> Schemas Tab:
All Schemas are shown in grey text (looks "disabled") and no checkmarks are shown for assigned Schemas, and also no checkmark is shown when assigning a new Schema to a project. When clicking on the checkmark, "Project assigned" notification is shown, and the Schema is assigned correctly, but no checkmark. Un-assigning Schemas is not possible.

**Comment by mephinet** [comment]
Thanks for reporting this bug! Work-around is to take the route Admin -> Schemas -> Project Assignment...
