### ISSUE TITLE
Image Manipulation

### ISSUE THREAD

**Issue by Jotschi** [gentics/mesh-ui#28]
As a user I want to be able to upload and resize images.

It should be possible:

* [x] To crop an image and override the existing image
* [x] To replace the image by a new image
* [x] To set a focal point within the image (currently not possible)
* [ ] ~~To rename the image file (currently not possible)~~ dealt with in #154

**Comment by michaelbromley** [comment]
Crop / resize implemented in https://github.com/gentics/mesh-ui/pull/102

**Comment by aschauerhuber** [comment]
~~To rename the image file (currently not possible)~~ dealt with in #154
