### ISSUE TITLE
Session timeout leads to API errors showing up

### ISSUE THREAD

**Issue by bebebee** [gentics/mesh-ui#285]
Mesh Ui is not used for a while, so that the session times out, but the user wants to continue using it and e.g. creates a new node.

Expected behavior: 
Either the session token can be refreshed, so that the user doesn't notice anything but the node is created successfully, or: The user is sent to the login page first to login again, and then the node is created.

Actual behavior:
API errors are showing up, and users are confused why this is happening - it's not obvious that logging out and back in again will fix the issue.

**Comment by pschulzk** [comment]
What [Mesh](https://github.com/gentics/mesh) or @gentics/mesh-ui Version do you use?

**Comment by bebebee** [comment]
Mesh: 1.1.1
Mesh-ui: 1.0.2
