### ISSUE TITLE
Page number does not reset when navigating to sub node

### ISSUE THREAD

**Issue by GlobaledaBeamaral** [gentics/mesh-ui#307]
Using Gentics Mesh 1.4.0:
How to reproduce the issue:
1 - Create a schema that is a container and name it "folder"
2 - Create a folder type node named "X"
3 - Navigate to folder "X"
4 - Create 11 folders named "1" to "11"
5 - Go to the second page
6 - Navigate to one of the folders in this page (let's suppose it's folder "7")
7 - Create a folder named "Y"
8 - The folder "Y" does not appear in the list (because of the query param ?p=2 and only one page exists)

The correct behavior should be reseting the page number when navigating to another subitem

**Comment by Jotschi** [comment]
Thanks for the report. We have already fixed the issue. The fix will be included in the next release.

**Comment by philippguertler** [comment]
This has been fixed with the UI Version 1.1.1 which was released with [Gentics Mesh 1.4.2](https://getmesh.io/docs/changelog/#v1.4.2)
