### ISSUE TITLE
Nodes that do contain dropdowns can only be published when dropdowns are not empty

### ISSUE THREAD

**Issue by bernhardriegler** [gentics/mesh-ui#31]
If a node has a field with defined allowed values it will be displayed as a dropdown when editing the node.
When no option is chosen the node can not be published. When clicking on "save & publish" button an error is visible in the js console. No error message is shown in the ui.

**Comment by philippguertler** [comment]
See also #121 
Was fixed with https://github.com/gentics/mesh-ui/pull/150/files#diff-6262215df78bab97634b6248b0b639cdR247
