### ISSUE TITLE
Update project creation dialog

### ISSUE THREAD

**Issue by Jotschi** [gentics/mesh-ui#42]
Add an option to directly apply anonymous permissions to the newly created project/base node.

We already got two issues because the users were not aware that they needed to apply additional permissions in order to be able to access the data. I think it would be helpful to incorporate the option to apply those perms during project creation.

Relates to https://github.com/gentics/mesh/issues/281

**Comment by aschauerhuber** [comment]
currently in the new UI a modal opens whereas in all other case (creating user/groups, etc.) we have a dedicated screen
