### ISSUE TITLE
Project management

### ISSUE THREAD

**Issue by michaelbromley** [gentics/mesh-ui#65]
Currently we have in the new UI a very basic implementation of CRUD on projects. This needs to be expanded so that there is a true list/detail separation for managing projects.

The detail view will also be used to display which schemas/microschemas are assigned to a project and manage tags.

**Comment by philippguertler** [comment]
- [x] List and detail view
- [x] Tag management
- [ ] Schema/Microschema assignment

**Comment by pschulzk** [comment]
Fixed in v0.10.6
